### ISSUE TITLE
View on gocom/danpu

### ISSUE THREAD

**Issue by petrgrishin** [infotech-ru/mysql-data-dumper#1]
View on https://github.com/gocom/danpu

**Comment by AntonTyutin** [comment]
An idea behind _mysql-data-dumper_ is little bit different. It makes snapshots of data (but not the schema), and restores initial state very quickly (because it doesn't drop/create tables).

however, thanx for the link )

**Comment by petrgrishin** [comment]
``` php
<?php
echo `gzcat ~/*.sql.gz | mysql -u root -pPassword dbName`;
```

**Comment by AntonTyutin** [comment]
) we are using it with behaviour tests for restoring DB to initial state. dumps should be callable from PHP and should run quietly fast.
