### ISSUE TITLE
Почему бы не использовать truncate table?

### ISSUE THREAD

**Issue by elfelrandcor** [infotech-ru/mysql-data-dumper#2]
Truncate быстрее, а тут как я понял таблица должна полностью очищаться, то есть никаких условий для delete не будет или в будущем они появятся?

**Comment by AntonTyutin** [comment]
задача: быстро восстановить исходное состояние БД. truncate быстрее на больших объемах данных, но с маленькими удаление и создание таблицы выполняется дольше (зависит от скорости записи на диск, у меня не на ssd диске полсекунды маленькая табла создается). а удаление (видимо из-за кеширования) происходит гораздо быстрее. вот такие дела

**Comment by elfelrandcor** [comment]
ясно, а автоинкремент ты не сбрасываешь? Delete же его не изменяет.

**Comment by AntonTyutin** [comment]
пока это не мешает (#3)

**Comment by elfelrandcor** [comment]
ok)
